<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Edit</name>
   <tag></tag>
   <elementGuidId>150f06a3-31d0-4169-b3e2-a6c3bd719e1c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='SetupCategory']/tbody/tr/td[3]/span/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.row_action_inner > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>69fbdbc7-89b0-45ee-a221-5c9c23f69396</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/jw/web/userview/expenseclaim/home/_/setupCategory?_mode=edit&amp;id=a916ad7d-0afe-46e0-97da-3731e78844ce</value>
      <webElementGuid>bc14ca81-a0f7-448f-8fbe-99f8185acb9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Edit</value>
      <webElementGuid>1a88f070-0b6d-45dc-a650-e8487bed6976</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SetupCategory&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[@class=&quot;row_action footable-visible footable-last-column&quot;]/span[@class=&quot;row_action_inner&quot;]/a[1]</value>
      <webElementGuid>0358f40b-7b18-47eb-a072-d1a6e2514547</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='SetupCategory']/tbody/tr/td[3]/span/a</value>
      <webElementGuid>dcf75249-e0b3-408f-ba96-73aac76c7723</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Edit')]</value>
      <webElementGuid>1a8a45a3-3844-43c8-a23d-f453ff038ab1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Food'])[1]/following::a[1]</value>
      <webElementGuid>510868b6-30a2-4384-8a69-09ccd7e2fcf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Expense Category'])[1]/following::a[1]</value>
      <webElementGuid>ec4fea52-96cb-468b-a3ec-5889537cd847</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Housing'])[1]/preceding::a[1]</value>
      <webElementGuid>eea867ab-684e-4eb0-bbd0-04a1772efd9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit'])[2]/preceding::a[1]</value>
      <webElementGuid>fc92e657-8e3c-422a-91c0-aac4735d2052</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Edit']/parent::*</value>
      <webElementGuid>0421bbe0-e859-48e1-9910-7fd35487acde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/jw/web/userview/expenseclaim/home/_/setupCategory?_mode=edit&amp;id=a916ad7d-0afe-46e0-97da-3731e78844ce')]</value>
      <webElementGuid>c9f5da58-3d2d-44f7-8a6b-996f82334bd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/a</value>
      <webElementGuid>a4723471-0abf-4a8d-baea-54791703d7f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/jw/web/userview/expenseclaim/home/_/setupCategory?_mode=edit&amp;id=a916ad7d-0afe-46e0-97da-3731e78844ce' and (text() = 'Edit' or . = 'Edit')]</value>
      <webElementGuid>3ec8b8d8-6d32-461c-ba62-9a704e1d3d89</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
