<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_show</name>
   <tag></tag>
   <elementGuidId>0415f6b0-12bf-40d7-bdb7-2b59cd7847bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Show']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.waves-button-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0ca264e4-883d-4bfa-b75f-9b070fcd8ecf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>0ff5e6d5-0d37-4f0b-857b-db9b2ed081c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>waves-button-input</value>
      <webElementGuid>e4036cdf-8f65-45b2-a598-78484b911a23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Show</value>
      <webElementGuid>643575b0-d56f-4a3f-b8fb-ab9348f0e092</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;filters_SetupCategory&quot;)/div[@class=&quot;filters&quot;]/span[@class=&quot;filter-cell&quot;]/i[@class=&quot;form-button btn button waves-input-wrapper waves-effect btn waves-button waves-float&quot;]/input[@class=&quot;waves-button-input&quot;]</value>
      <webElementGuid>ed6654a4-43b5-4c75-a2f4-7b6f9fe22ac9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Show']</value>
      <webElementGuid>5add7216-da2e-4faf-85a3-575981d9961f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='filters_SetupCategory']/div/span[2]/i/input</value>
      <webElementGuid>6a939f1a-399f-486f-a705-2cb60ac57928</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i/input</value>
      <webElementGuid>990ae48c-4ae9-4086-8059-4c53bf386fe6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit']</value>
      <webElementGuid>843e935b-89ce-4223-b04f-2045ed18486f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
