<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_New</name>
   <tag></tag>
   <elementGuidId>fcf43fe7-e67e-41a5-991f-d69ac5b07b91</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='d-5477653-ac']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;d-5477653-ac&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6282f6ca-981f-4848-97f0-7572d180ff6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-href</name>
      <type>Main</type>
      <value>/jw/web/userview/expenseclaim/home/_/setupCategory?_mode=add</value>
      <webElementGuid>23f8c199-f045-4461-b09c-171b7ae6ccf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>d-5477653-ac</value>
      <webElementGuid>296fc9ff-fe7f-4981-9496-8c29d06c7cf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-button btn button  waves-effect btn waves-button waves-float</value>
      <webElementGuid>635308ec-ab35-4299-940b-70a7c0f87919</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>CRUD_New</value>
      <webElementGuid>6b91002a-55b2-4f48-b304-9879dbd56b03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>New</value>
      <webElementGuid>e38ce40c-5f7a-4eae-8ed2-0b5cc5cda5a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/main[1]/div[@class=&quot;datalist-body-content&quot;]/div[@class=&quot;dataList&quot;]/form[2]/div[@class=&quot;actions top left&quot;]/button[@class=&quot;form-button btn button  waves-effect btn waves-button waves-float&quot;]</value>
      <webElementGuid>5560b4a3-adf0-4877-a49f-7ce6d5498f18</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='d-5477653-ac']</value>
      <webElementGuid>826b08bc-64c5-4629-8073-e6b336181330</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/main/div[2]/div/form[2]/div/button</value>
      <webElementGuid>9f419b34-06f7-4b57-9b79-8cc83cab3315</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='List: Expense Setup Category'])[1]/following::button[1]</value>
      <webElementGuid>7567794c-5249-4b6e-8dea-72840c869e16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Set Up Expense Categories'])[1]/following::button[1]</value>
      <webElementGuid>fb241dd1-ae00-4538-9229-8e7390e90ec6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[1]/preceding::button[1]</value>
      <webElementGuid>b7220e7a-f041-44ac-ac0c-5d79c4c7e5de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Show All Details'])[1]/preceding::button[2]</value>
      <webElementGuid>4cbd0c0c-0cb3-4458-a3ba-5ba64b66be7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='New']/parent::*</value>
      <webElementGuid>068612d3-55f8-48ec-a436-133de031e47b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>ab53a8c3-4628-45f0-bdc6-721ed73b9c2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@name = 'd-5477653-ac' and (text() = 'New' or . = 'New')]</value>
      <webElementGuid>0fd7d1e1-717d-49f1-9e72-509de3ce9b68</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
