<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Delete</name>
   <tag></tag>
   <elementGuidId>0c5229e5-eb62-4e1a-a7c0-09bcba42fcb4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@name='d-5477653-ac'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ae8456b2-3f65-430c-9425-1e3baf686657</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>post</value>
      <webElementGuid>1a2562fc-20da-4275-9a13-eefc4a946bc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>d-5477653-ac</value>
      <webElementGuid>9c38d13c-551a-46ee-aab8-710c265cdfcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-button btn button btn-danger waves-effect btn waves-button waves-float</value>
      <webElementGuid>94c27ffe-b1d7-49e3-82dc-333b6b8a8753</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>CRUD_DELETE</value>
      <webElementGuid>7c03b8d8-37ab-4938-871c-1cdcd71d69a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-confirmation</name>
      <type>Main</type>
      <value>Please Confirm?</value>
      <webElementGuid>754be0c8-9dab-403a-b7b0-20533e57bdda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Delete</value>
      <webElementGuid>a049e61e-05d1-4392-bef9-cad97b7fb403</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/main[1]/div[@class=&quot;datalist-body-content&quot;]/div[@class=&quot;dataList&quot;]/form[2]/div[@class=&quot;actions top left&quot;]/button[@class=&quot;form-button btn button btn-danger waves-effect btn waves-button waves-float&quot;]</value>
      <webElementGuid>30062498-24e0-430d-b14a-42bcbe56e937</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@name='d-5477653-ac'])[2]</value>
      <webElementGuid>7a7d198f-f413-4aa8-a7ef-361c50f9059c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/main/div[2]/div/form[2]/div/button[2]</value>
      <webElementGuid>89ed7008-c410-4666-89bd-c91bf25ba50b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New'])[1]/following::button[1]</value>
      <webElementGuid>8789bec2-c75a-4e76-9b86-4464b552c557</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='List: Expense Setup Category'])[1]/following::button[2]</value>
      <webElementGuid>053bebe8-048d-457f-b626-5eb17cef9ea2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Show All Details'])[1]/preceding::button[1]</value>
      <webElementGuid>bbf5a2fb-45bf-41c3-a799-dc832e30f973</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hide All Details'])[1]/preceding::button[2]</value>
      <webElementGuid>2acb1664-39bd-409d-901f-0ad93e51a2ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Delete']/parent::*</value>
      <webElementGuid>9edcb198-2f8a-4090-86f6-87eb50891843</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>5d58d436-7ffe-4b42-a516-73cb92eade98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@name = 'd-5477653-ac' and (text() = 'Delete' or . = 'Delete')]</value>
      <webElementGuid>cf99b2ca-7853-49ff-a873-75d4424d3220</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
