<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_complete_approver</name>
   <tag></tag>
   <elementGuidId>7b8bee8f-6176-4371-9c22-cb22d7cdd808</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='assignmentComplete']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#assignmentComplete</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7d8fbcb6-ca13-48ab-9cd3-871579d28ea6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>assignmentComplete</value>
      <webElementGuid>d0a18726-bab8-426f-bbef-dd9f37a39b66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>assignmentComplete</value>
      <webElementGuid>93854461-b2f6-4bb6-9a35-38a32cde81ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>waves-button-input</value>
      <webElementGuid>abe5d9e0-714e-44bd-88d5-f2414caeffe4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>8eb1b52c-e4aa-4e27-8d36-93be0d81c878</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Complete</value>
      <webElementGuid>e72e82eb-01f2-49dd-bc16-f39d8871279f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;assignmentComplete&quot;)</value>
      <webElementGuid>326e8f90-332b-4465-939b-0ad6c743d750</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='assignmentComplete']</value>
      <webElementGuid>e7f09a87-18eb-449c-8458-1181fa13da81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='section-actions']/div[2]/div/i/input</value>
      <webElementGuid>2100ecf2-67a8-4f9e-b920-f6203ea22e1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i/input</value>
      <webElementGuid>e2869119-be60-428c-8d97-6698e61d071d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'assignmentComplete' and @name = 'assignmentComplete' and @type = 'submit']</value>
      <webElementGuid>5d918df8-f450-4fbb-90fd-e2097304da01</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
