<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Total Amount_total</name>
   <tag></tag>
   <elementGuidId>0faf4ae5-04ab-49ea-8114-519b415d0195</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#total</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='total']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>96570bbd-2346-418a-851a-ebb1f82dc81c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>total</value>
      <webElementGuid>bcf3616e-6467-4509-b20a-5d352c7a0f40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>total</value>
      <webElementGuid>4cba249a-8d0b-437a-9e45-60da9af267cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>48789dbf-4618-494f-a923-16bed6714cea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>calFiel_4635</value>
      <webElementGuid>ebba37a1-36bd-4df9-a27c-bc8d5c9739df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;total&quot;)</value>
      <webElementGuid>e348b6d9-aee5-452f-b657-3df45b4b815b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='total']</value>
      <webElementGuid>c62bbf9c-4d62-4db8-bcb9-9cfc7d079d9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='section3']/div[3]/div/input</value>
      <webElementGuid>28c1e019-8a1c-4f43-827b-2779f2401801</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>80b417d8-d3df-454b-8cac-f2f97ea36c70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'total' and @name = 'total' and @type = 'text']</value>
      <webElementGuid>2c4e94e2-f597-4eb5-aeb8-53466412ce98</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
