<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Transportation_handsontableInput</name>
   <tag></tag>
   <elementGuidId>6b531abe-6cfb-4cab-b0a7-810edad53034</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[2]/div[1]/div/div[2]/main/div[1]/fieldset/form/div[2]/div[2]/div[2]/div[2]/div/div[1]/div/div/div/table/tbody/tr/td[3]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;spreadsheet_spECD_4630&quot;)/div[@class=&quot;handsontableInputHolder&quot;]/textarea[@class=&quot;handsontableInput&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>079cbef6-22fb-4059-8b9e-a5dc690c8c5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>85bafb96-008d-47e8-905e-38e5767350d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>handsontableInput</value>
      <webElementGuid>d5325758-9219-4ac9-aacc-11492675ff1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>abcb7cde-30f2-4981-8c5a-72a68901c650</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;spreadsheet_spECD_4630&quot;)/div[@class=&quot;handsontableInputHolder&quot;]/textarea[@class=&quot;handsontableInput&quot;]</value>
      <webElementGuid>96494cd7-2743-40fd-a3cc-d81b89a62979</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='spreadsheet_spECD_4630']/div[9]/textarea</value>
      <webElementGuid>a947bcfc-56b8-4eec-ac79-7c73b4679afe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/textarea</value>
      <webElementGuid>0d6c389f-658c-4957-8f0b-4e56af5a9a64</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
