<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_area_approver_remark</name>
   <tag></tag>
   <elementGuidId>449dd961-ea1a-4d6d-a94f-e404f7507594</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='approval_form_ExpensesApprovalEntry_comment']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#approval_form_ExpensesApprovalEntry_comment</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>de415924-2e1a-4f62-aeaf-6f926ee4b5fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>approval_form_ExpensesApprovalEntry_comment</value>
      <webElementGuid>e0dc2577-6239-4834-88bd-a66ddc775737</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>approval_form_ExpensesApprovalEntry_comment</value>
      <webElementGuid>4dd5e4b8-cc94-4ba9-9c55-b30ef5e21033</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>4d1c6f10-02d5-43a7-9c85-b572525055f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>66dc8fac-b6e8-4a40-8768-0394c4c638d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;approval_form_ExpensesApprovalEntry_comment&quot;)</value>
      <webElementGuid>299125b2-eca7-443f-9bf6-99f4c04ae293</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='approval_form_ExpensesApprovalEntry_comment']</value>
      <webElementGuid>0f49126c-f9e0-427b-a628-a2c80e5e460b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='approval_form_ExpensesApprovalEntry_section1']/div[2]/div[2]/textarea</value>
      <webElementGuid>d42d6529-b6fe-4c86-a819-b87c98bbae85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/textarea</value>
      <webElementGuid>26339527-7c38-4b7a-8f64-f0646e87f361</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'approval_form_ExpensesApprovalEntry_comment' and @name = 'approval_form_ExpensesApprovalEntry_comment']</value>
      <webElementGuid>efd9a2e9-6e56-49fa-a300-87af03f73614</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
