<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>set_purpose</name>
   <tag></tag>
   <elementGuidId>22a951c6-f1cb-4ac9-b8d8-a55b19157ed0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>textarea.handsontableInput</value>
      </entry>
      <entry>
         <key>IMAGE</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[2]/div[1]/div/div[2]/main/div[1]/fieldset/form/div[2]/div[2]/div[2]/div[2]/div/div[1]/div/div/div/table/tbody/tr/td[3]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@tabindex = '-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>05e996c0-4ec4-4202-b9ef-d323dcdec3b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>ead66856-62fa-4335-a4a1-167be099cb57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>handsontableInput</value>
      <webElementGuid>7f7b2dd9-2de5-4200-ad00-a4db6d6a187b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;spreadsheet_spECD_11027&quot;)/div[@class=&quot;handsontableInputHolder&quot;]/textarea[@class=&quot;handsontableInput&quot;]</value>
      <webElementGuid>e297c030-3fdb-4251-b250-7ceab65e3d51</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='spreadsheet_spECD_11027']/div[6]/textarea</value>
      <webElementGuid>56a5ecfa-d2df-40d6-971b-11da59797492</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/textarea</value>
      <webElementGuid>462344ad-9be2-4cf9-8777-51a24a4d0a50</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
