<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>set_Amount</name>
   <tag></tag>
   <elementGuidId>6c924684-29fa-49db-87dc-151e171aa48f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>textarea.handsontableInput</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='spreadsheet_spECD_1641']/div[7]/textarea</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@tabindex = '-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>6954a009-9e1c-42ce-807e-e36f7bafdbd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>ba0622b4-5821-448d-b2e8-ca03d9e8d117</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>handsontableInput</value>
      <webElementGuid>0f5b069e-91bc-405b-80ed-2409a6abb167</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;spreadsheet_spECD_1641&quot;)/div[@class=&quot;handsontableInputHolder&quot;]/textarea[@class=&quot;handsontableInput&quot;]</value>
      <webElementGuid>88d6a8cc-506c-4666-b9ce-590650690d1b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='spreadsheet_spECD_1641']/div[7]/textarea</value>
      <webElementGuid>8822a6e3-0787-42c7-bc09-deb7f05eadc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/textarea</value>
      <webElementGuid>9226d314-928c-442d-a9a0-fe84f89023a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
