<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_category-expense</name>
   <tag></tag>
   <elementGuidId>6d3a56d8-3e3f-4157-82b1-cde5d4ef6286</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[2]/div[1]/div/div[2]/main/div[1]/fieldset/form/div[2]/div[2]/div[2]/div[2]/div/div[6]/textarea</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>textarea.handsontableInput</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;spreadsheet_spECD_11027&quot;)/div[@class=&quot;handsontableInputHolder&quot;]/textarea[@class=&quot;handsontableInput&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>c08912ed-89b7-488d-979c-cb92ee8a2f23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>324901bd-d025-47ed-a7c8-3b26646f8b48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>handsontableInput</value>
      <webElementGuid>02189608-6808-4fc2-81ae-ef349141f2fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>bd359374-3a2b-4211-a3e9-105d949fac5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;spreadsheet_spECD_11027&quot;)/div[@class=&quot;handsontableInputHolder&quot;]/textarea[@class=&quot;handsontableInput&quot;]</value>
      <webElementGuid>4d4d6ef4-2b71-4c82-8bdd-040357421ea9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='spreadsheet_spECD_11027']/div[6]/textarea</value>
      <webElementGuid>876da4ff-9c5c-46d9-8877-fc141716aeca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/textarea</value>
      <webElementGuid>abf29976-725b-41cc-86a0-e20bb698c880</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='spreadsheet_spECD_3943']/div[7]/textarea</value>
      <webElementGuid>4ee550d0-497f-420d-88af-09787d91d0da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/textarea</value>
      <webElementGuid>c3b4928a-34c6-4002-983a-e4284fadf431</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
