<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_8</name>
   <tag></tag>
   <elementGuidId>bc77f4e5-aea2-4d0f-8137-cdade71cc402</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.pika-button.pika-day</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'button' and (text() = '8' or . = '8')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ebb465ac-74c8-4a3e-9621-c7a7cd89faf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pika-button pika-day</value>
      <webElementGuid>35b5eb16-5150-42c0-ad6d-9a3352c3ca05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e3828807-650a-4c95-bea1-5278861b2cce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pika-year</name>
      <type>Main</type>
      <value>2024</value>
      <webElementGuid>4152b8a6-9cc1-49f5-97c0-61f1be52b3e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pika-month</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>bb6f0786-2a64-4e4b-8d6b-b7970b9f9101</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pika-day</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>e33fa9d3-a4f4-4f4e-b02d-de7b1ec51496</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>a7c3a58f-a4cb-4078-864e-1011c36ae68f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;myin&quot;)/div[@class=&quot;htDatepickerHolder&quot;]/div[@class=&quot;pika-single&quot;]/div[@class=&quot;pika-lendar&quot;]/table[@class=&quot;pika-table&quot;]/tbody[1]/tr[1]/td[4]/button[@class=&quot;pika-button pika-day&quot;]</value>
      <webElementGuid>c9dc7ac0-72a3-47d6-8d22-7121b284fca6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[3]</value>
      <webElementGuid>94831d1b-4143-4446-acbc-2e6a274ab867</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='myin']/div[5]/div/div/table/tbody/tr/td[4]/button</value>
      <webElementGuid>dcb8e118-a174-4ca3-947d-84b7f4a1954c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sat'])[1]/following::button[1]</value>
      <webElementGuid>22b0ac41-8f70-4a59-9417-5aee25b18c45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fri'])[1]/following::button[1]</value>
      <webElementGuid>96a4f67d-aea6-47e9-becd-772ff896b32a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/button</value>
      <webElementGuid>ac7487d1-e03a-4a63-8457-8119b1852aae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '1' or . = '1')]</value>
      <webElementGuid>96403d6c-7333-4681-bc48-7890eb7accaa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
