<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_1 - Copy</name>
   <tag></tag>
   <elementGuidId>700f5452-9b39-4359-9b45-ff19cc865ffa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[5]/div/div/table/tbody/tr[1]/td[4]/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.pika-button.pika-day</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'button' and (text() = '1' or . = '1')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e43676bf-61a3-4919-8e47-fb05def1c264</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pika-button pika-day</value>
      <webElementGuid>985b8f52-5420-4c51-8e33-ba3b65fa1600</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>514f65e2-c497-46d9-9681-73d3fb0b7650</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pika-year</name>
      <type>Main</type>
      <value>2024</value>
      <webElementGuid>5999ec50-b698-4144-88df-7fd682c42926</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pika-month</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>01cf0248-ee80-458f-be80-1f6cd3cbf483</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pika-day</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>64748f3c-a567-486a-817d-7136ef740a48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>b22b308f-3dab-4609-916b-d2d8a16a1705</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;myin&quot;)/div[@class=&quot;htDatepickerHolder&quot;]/div[@class=&quot;pika-single&quot;]/div[@class=&quot;pika-lendar&quot;]/table[@class=&quot;pika-table&quot;]/tbody[1]/tr[1]/td[4]/button[@class=&quot;pika-button pika-day&quot;]</value>
      <webElementGuid>90200182-c772-4737-aeb8-1f62b52d9122</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[3]</value>
      <webElementGuid>f0f29b32-d7c9-44bf-b366-33374b4e4f20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='myin']/div[5]/div/div/table/tbody/tr/td[4]/button</value>
      <webElementGuid>35236606-fc7f-4ff5-b4e3-c51e12823d24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sat'])[1]/following::button[1]</value>
      <webElementGuid>11237ae4-7fbf-4d60-ae98-6e3cec23b9c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fri'])[1]/following::button[1]</value>
      <webElementGuid>cce3b143-d3af-4346-b05b-22ae9c4dedf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/button</value>
      <webElementGuid>6569a79e-66fb-4cde-9885-912b7dd791b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '1' or . = '1')]</value>
      <webElementGuid>b0b099f7-3b6b-40c0-8e97-a24b440ef8bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
