<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_20</name>
   <tag></tag>
   <elementGuidId>a62200d4-612c-4a9c-a294-58b17474ddbb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.pika-button.pika-day</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'button' and (text() = '20' or . = '20')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>540153d5-353f-4af6-9a52-209f0eaed7f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pika-button pika-day</value>
      <webElementGuid>7fda0d03-b618-40d1-b1ad-dc8b06a44711</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>452d848b-c3b9-43b2-bdcc-934c66004f17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pika-year</name>
      <type>Main</type>
      <value>2024</value>
      <webElementGuid>c7127901-a549-4e99-b33f-2518caf8bcdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pika-month</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>286169c7-a24c-4b7f-9d22-384788599839</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pika-day</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>2d3aa18c-cf4d-440b-83e6-10fae5af88ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>9d7055ca-74bc-4e91-9b47-9cc7d9a9e1db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;myin&quot;)/div[@class=&quot;htDatepickerHolder&quot;]/div[@class=&quot;pika-single&quot;]/div[@class=&quot;pika-lendar&quot;]/table[@class=&quot;pika-table&quot;]/tbody[1]/tr[1]/td[4]/button[@class=&quot;pika-button pika-day&quot;]</value>
      <webElementGuid>8681036c-d01d-4516-8739-3ab5c14ef854</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[3]</value>
      <webElementGuid>896448aa-5872-4908-b0b0-b822ddc9e508</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='myin']/div[5]/div/div/table/tbody/tr/td[4]/button</value>
      <webElementGuid>d40a638f-7aac-4e8a-b7d5-84baf8f6c794</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sat'])[1]/following::button[1]</value>
      <webElementGuid>a6b65941-6af0-4c97-b611-b353da2f1e1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fri'])[1]/following::button[1]</value>
      <webElementGuid>8c700803-174b-4c61-a9c3-c1213e022955</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/button</value>
      <webElementGuid>95b4bd5f-40d2-48db-a7b5-a42f9a8b719e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '1' or . = '1')]</value>
      <webElementGuid>30d9dc5e-a401-4ca3-a0c6-e852bd1ead6f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
