<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_12</name>
   <tag></tag>
   <elementGuidId>a795d786-5ea9-4ce3-901d-eac0204be6f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.pika-button.pika-day</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'button' and (text() = '12' or . = '12')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8efd986f-b5e6-4849-9bb0-7661b1f48db4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pika-button pika-day</value>
      <webElementGuid>d3f1c2a0-8d8d-404b-a33d-37942f60752e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a426cdb7-5d15-477f-892e-8588e78b7d8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pika-year</name>
      <type>Main</type>
      <value>2024</value>
      <webElementGuid>9e55a29d-a292-4c94-9971-37ac03374261</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pika-month</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>1aa8b25e-4ba1-4d09-a133-4125d8bccdfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pika-day</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>89b7922c-ee45-4730-b072-81624035fc7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>05c1ddcf-e529-4ce5-8151-f3be0d3a3fb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;myin&quot;)/div[@class=&quot;htDatepickerHolder&quot;]/div[@class=&quot;pika-single&quot;]/div[@class=&quot;pika-lendar&quot;]/table[@class=&quot;pika-table&quot;]/tbody[1]/tr[1]/td[4]/button[@class=&quot;pika-button pika-day&quot;]</value>
      <webElementGuid>686d53c3-dc59-4b92-81f7-91bf133f0814</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[3]</value>
      <webElementGuid>0ad367d9-b376-4ead-a184-980353d61969</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='myin']/div[5]/div/div/table/tbody/tr/td[4]/button</value>
      <webElementGuid>9d63cbd3-7b9c-469f-8fe1-aebaee9d737a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sat'])[1]/following::button[1]</value>
      <webElementGuid>5d15ef3d-8b4c-4dda-a6b3-b418d949cd04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fri'])[1]/following::button[1]</value>
      <webElementGuid>48b7238b-7c22-4514-bfa8-ea33b150b53c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/button</value>
      <webElementGuid>b721ef5a-9616-4b79-b30b-eee4ef557f5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '1' or . = '1')]</value>
      <webElementGuid>4740fcd1-cf2c-42ee-a2c7-2ce02e1247f0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
