<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_text_expenses_category_pencarian</name>
   <tag></tag>
   <elementGuidId>76d29c14-200c-4768-bb45-3c82f0142e75</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='d-5477653-fn_Category']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#d-5477653-fn_Category</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1dc0f9ec-86d2-4be5-be27-58fb3f51c595</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>d-5477653-fn_Category</value>
      <webElementGuid>e363f2e9-769e-4ff9-941e-8ccfa4815d73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>d-5477653-fn_Category</value>
      <webElementGuid>aaeee890-6a4a-43de-8b73-98a72916c568</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4f17136f-f415-4bf4-a15d-cc453d090986</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>579cc3e0-6970-46ad-b8d7-172c5223573a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Expense Category</value>
      <webElementGuid>cb2c1244-d31a-4059-a7ec-6a38bb33679f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;d-5477653-fn_Category&quot;)</value>
      <webElementGuid>afc6cfca-4500-4720-91d9-d2e0f56ea84c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='d-5477653-fn_Category']</value>
      <webElementGuid>590b7152-7a4f-4173-92b1-6f68a0d620f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='filters_SetupCategory']/div/span/input</value>
      <webElementGuid>96a641a0-adb0-430a-baf1-36096f39c584</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>4f3961de-0087-4f7d-8640-ed7aafeac767</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'd-5477653-fn_Category' and @name = 'd-5477653-fn_Category' and @type = 'text' and @placeholder = 'Expense Category']</value>
      <webElementGuid>50dba14d-580e-4471-97d5-89413a75c336</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
