<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Create A New Expense Claim</name>
   <tag></tag>
   <elementGuidId>ad5ba887-e850-4287-8c9f-02f2d7a5801b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='d-1088314-ac']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;d-1088314-ac&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4e58defd-c38d-4885-907f-a1d542da4259</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>_self</value>
      <webElementGuid>e3b8a66b-966a-4189-9817-5cccdb3993ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-href</name>
      <type>Main</type>
      <value>new_claim</value>
      <webElementGuid>be45db7b-dfde-4b1e-b064-923f668214b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>d-1088314-ac</value>
      <webElementGuid>ab8ab84e-eafa-4afa-8456-56cea6f8cf57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-button btn button  waves-effect btn waves-button waves-float</value>
      <webElementGuid>c270af90-5078-4449-9a6f-bcd67c8a5e08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>action_0</value>
      <webElementGuid>ade98c6d-442b-46ac-8ac9-901ebc834bed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create A New Expense Claim</value>
      <webElementGuid>71571aec-0ec7-4fae-abe9-066d9ded5f2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/main[1]/div[@class=&quot;datalist-body-content&quot;]/div[@class=&quot;dataList&quot;]/form[2]/div[@class=&quot;actions top left&quot;]/button[@class=&quot;form-button btn button  waves-effect btn waves-button waves-float&quot;]</value>
      <webElementGuid>0004aeb6-2a28-404f-bf07-cf0cd38f676d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='d-1088314-ac']</value>
      <webElementGuid>1602b8eb-bd41-44ab-9f1b-44e2d7e41f2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/main/div/div/form[2]/div/button</value>
      <webElementGuid>a445337a-a541-4359-81ba-e406f8456968</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[1]/following::button[1]</value>
      <webElementGuid>518e9c52-54d5-4eb2-85ce-5f6c0d9eb0d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date Created'])[1]/following::button[1]</value>
      <webElementGuid>c43d689b-90d9-4e76-beb3-722f546da72c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Show All Details'])[1]/preceding::button[1]</value>
      <webElementGuid>b54cf52a-5362-43f7-9adf-54a8cfd1cae4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hide All Details'])[1]/preceding::button[2]</value>
      <webElementGuid>5a4f5d8a-084c-4e32-babc-21840ddefd64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Create A New Expense Claim']/parent::*</value>
      <webElementGuid>88ffc7a8-0f94-4b60-b48f-274857f0e2c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>d361adaf-0c08-4821-9811-fb46dfbb10f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@name = 'd-1088314-ac' and (text() = 'Create A New Expense Claim' or . = 'Create A New Expense Claim')]</value>
      <webElementGuid>0249196e-aa6a-4611-8917-66878f81bf49</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
