<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__assignmentComplete</name>
   <tag></tag>
   <elementGuidId>e8755fb7-0e10-49b6-8ec6-61f78d66c440</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='assignmentComplete']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#assignmentComplete</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4cf619ae-483c-4da4-9fca-2028630c2a49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>assignmentComplete</value>
      <webElementGuid>3ef0778c-4770-452c-8e58-5e9fd50a2149</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>assignmentComplete</value>
      <webElementGuid>689e2e0b-f81e-4fe1-a079-b0f3efe70cb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>waves-button-input</value>
      <webElementGuid>79882824-7730-42bc-a617-93da01d4e3f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>9c587b8f-443c-4024-bd62-6dfddc7bf37a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Continue Next Screen</value>
      <webElementGuid>adf54509-eb13-416e-9102-795d85473690</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;assignmentComplete&quot;)</value>
      <webElementGuid>54158746-22b4-4cfe-a332-2add70e56562</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='assignmentComplete']</value>
      <webElementGuid>4f199955-ad96-4823-8ab3-617d320028a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='section-actions']/div[2]/div/i/input</value>
      <webElementGuid>4f9ef81b-d174-4b77-a47d-0cb31ac14d8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i/input</value>
      <webElementGuid>53994638-781f-4c65-8577-09b93ab9a6c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'assignmentComplete' and @name = 'assignmentComplete' and @type = 'submit']</value>
      <webElementGuid>364087e6-6e2b-46ff-9df4-39be4e09d4be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
